name: Generate Pac-Man Animation

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
    
  workflow_dispatch: # Permite execução manual

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Ferrari65  # << seu nome de usuário fixado

      - name: Publicar SVG na branch 'output'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: ./
          commit_message: "Atualizar Pac-Man contribution graph"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
