# Seu arquivo snake.yml com cores amarelas:
name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Ferrari65
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?color_snake=FFCB05&color_dots=F59E0B,FDE047,FACC15,EAB308&background_color=0d1117
            
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
